### ISSUE TITLE
GUI for running a race

### ISSUE THREAD

**Issue by malsaker** [heinek/ITimeU#11]
1. No error message when trying to enter start numbers without selecting a checkpoint. just nothing happens
2. It's hard to know by default that a checkpoint in not chosen before you push the button, even though you have selected an item from the dropdown. And it's no GUI response when pushing the button for selecting a checkpoint.
3. Maybe it should have been a bigger visible status field in top of the page showing the actual selected checkpoint (and also saying "No checkpoint selected" until you have seleced one)

**Comment by ArnsteinJohansen** [comment]
What if the "first" checkpoint is selected when you enter the page, is that sufficient?

**Comment by malsaker** [comment]
Yes, I think so.
The most important thing I believe is that it's clearly for the end user whether or not he has selected a checkpoint, and what checkpoint he is working on right now.
