### ISSUE TITLE
Imported information not saved in DB

### ISSUE THREAD

**Issue by malsaker** [heinek/ITimeU#4]
When importing athletes from FriRes; athlete class, club and startnumber is not saved to the database.

**Comment by yngvark** [comment]
Hei

Jeg ser du har begynt med litt testing, og jeg ser at det er noe kode jeg
desverre ikke fikk sjekket inn da jeg dro, og jeg har ganske drlig tid om
dagen til  commite og sjekke feil.. Hva hvis jeg bare pusher til en ny
remote branch, s kan dere prve  f denne koden til  funke?

Det kan nok ha noe med denne feilen  gjre.

Yngvar

**Comment by malsaker** [comment]
Heisann Yngvar

Ja, jeg synes å huske at koden du/vi lagde lagret også klubb og klasse til databasen fra det vi importerte fra FriRes. Ivertfall gjorde det det når vi testet lokalt.
Bare sjekk inn til ny branch ja og så ser vi om vi får det til å funke.

Magnus
